# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(default=1, verbose_name='month')),
                ('day', models.PositiveIntegerField(default=1, verbose_name='day')),
                ('beginTime', models.FloatField(default=10)),
                ('endTime', models.FloatField(default=10)),
                ('timeLength', models.FloatField(default=10)),
            ],
        ),
    ]
